### ISSUE TITLE
Not Work !!

### ISSUE THREAD

**Issue by GabBiswajit** [koningcool/LoadAllWorlds#17]
I have 500 Worlds And It's Not Load All After Load Some It's Unload All Again

**Comment by JustJoostNL** [comment]
This plugin is outdated and support and updates won’t be given anymore.

**Comment by GabBiswajit** [comment]
Why @JustJoostNL

**Comment by JustJoostNL** [comment]
Won't go further into that, plugin is outdated and won't be updated, support also won't be given.

**Comment by GabBiswajit** [comment]
I use pm4 version and i think the problem with server want to increase anything in server fills i think it's because can't show all world load message that's why

**Comment by JustJoostNL** [comment]
As I said before, I won't help you. I will lock this issue now.
